def decoded(file_content):
    vowels = {'a', 'e', 'i', 'o', 'u'}
    decoded = ""
    lines = file_content.splitlines()

    for line in lines:
        vowel_count = sum(1 for char in line if char.lower() in vowels)
        decoded += " " if vowel_count == 0 else chr(96 + vowel_count)
    return decoded


file_content = """
kskpnmmerynrthtullixbwjvfxsqdhngmphjjwgoaodzzalckqiqcybpgevf
phpqdrlmzxvbcdpygrfsjnnhmjgxlkfbmcsckftwvqslbqtyktdgwzhnrjzy
beiiruqwogjepegscounuaufnhoivqwczkxisezaeitaydfrmbdvaxoatlyp
sllkcwkqgfbfvpxkmmajcidjgwbtpsfouehidlvqmzagrnxdroceyhzyhtnj
dzfanraryeixewwztfndkhpqujgbxrsgumwpmtskcbeitsqylvhjavocvlox
suwgrkypinaxtlmdqejwkdhfrvevtpzfljzmrxynbhogstwcbcaisoeqvuax
flyjmtbdqrwhkggdhpzxhjjrwrtgzfmxkwykyvstmqfpsclvqclzpnsnxbvn
ydsvouygppgsoartmikxqftwvwulqwrfhsrnnzcaejvizabhcidjekxetlbm
pnmdcjftyflrmhtfbgzczxlzlddvpwjvskhgmwrcnsakqjbghybytswvxkxq
lzsbzmadprylvkukvennyiupatjepqqjqcogffxsbgatomsixrhtwhwdcnvr
ipbvjknhbztmxxlvjkmduldwlyggfhnmdcqjbefspcqarfkowzpnzghsyctr
xvrhnzvvqxtdsgdfsmcjbtjhyqkhbbglnflckwnkwzydpmrtlwpcfmpyjxgz
eajxoberlkidiucameeruwaovezlgpvmuaniwjkphnhuiiytatsqsooxofuq
twrxwviiadnapnlzhgmwqtfyigseoquovjsloarmpuekhuvjbxkcyedbcfzx
ehmqiguoxewpysooukliqsvjbrmprnebuxzzdnwifcueadlcaavyatatigof
qccnjdxbkwhwjpgkbtmnczgpqvyfstfvlbfgllwrvqpmsrdrxdyhnmtzjksh
twrqwzplkjdlcgsmvjpbxmhcfyzytqkrktnzvgsnlhfyaqrsbpjmgwvnxdhx
egadnhbcfvpoybgrsfcwlpeqziwaoebirqusxvoxytzkkcijmdhujzndmlta
zvfttzbgmfyrndwfgnzhdnskxvrchjwxmcphqclrlpybxwtgkvsqsmbydjqp
rncpzqoinqdfiwlbqbkojjasahevxpepiyxveduhcgfouwmtzamrkrstgyul
altcsqdwylhxhnpnwmtrgdkvawvsjybpvqujxebboxzqmyzpfisfrrtgnckz
gbfmhdvzlzvkdjpoljmwjwmkcknnqausarqelpiycznhggxytbxchdsftbrf
vzjbigyklxccfparvwezdbgyymgtdcjxqjnxwfplhhksuwhrmbkolstnzdfq
emutcmkqzaghgsiopnijlexdqoyujrwdwofevebxzcytlnfhrvaaipsuiabk
ldnmqfmwpbxtjxqhnczrbsyzchywykhbwpvdszclgnjvtlgprxfdrjgfkqkm
znooobmagvpfydueaxbaeeesxiehkjrstvuqoipiyalrwmqaitzuwniucuco
atjqburyyqcxozmpsbgnrfuaimkqxhevpcazguwlknoeirhpsftloivdejdw
brueyuwcegtqljaonboczakpauuvtrdgzkiaxdiqnfesslamopemifoyjhhi
tdjpklzwxflcnkgtghxqbkyjymmzgvrfqszfphbwrtdscdymbqnhjrcsvnlp
cdqgrfpxbkrmldlfxnipwvjbyryjhnttbshxdcqqzscazzpyewntgwkvmsvm
gkpqwwxfdbzjjlgdhrlvxsprgfncanmyfqtchkrbzkydqlcphmmyvstsbjzn
rcrnknpkpvnzefrflqauwbsijdaoghutegqysjmcmlpxbivqxeowiaydzoht
zlnftgdtqfklvlxqnkcpsdcyswwqhkfdcgmxyrtvjybprzrbbhmswnmpxjvz
iwzbeoxfmhxksyawrsdcpvyfqulgenmbuajndaveptiztilrsvtcqogwkohj
mqfkzoznwydrdhaoupsjinbepwvvtlxecasoqrjvektclgxbtgufiyisuham
iurfuvlgamtufdmenzyqijcdrkaslaxaswztoiixqooyenhbpjgheekpouvw
rczsjqxkbytpkzpmdvllbhbrqmvctfyswvdpfnmggfwjhytdxnqchgsxzwnr
qoawzxnpngjufrevqkczossbwafijvpbgilhadmumleyeiiahxruydttceko
fzebxvbmrfcmynthtynrqsspclmpotxdhifsvnuqzwjgdklkrqggkhplwajj
manqkjsqsjuslendfytkiwfgjovrrzlbtnmxcfqmrlzwyhcdhgpkpbxpavhg
vulewyempneyuujbvjoozoaahormgiixawxtqdafzichualrsenpqkistckb
kcwcgxioqdohrnnvuitzkpigxeporqwafjvmdimfyuylahsboleteueabjsa
cybfayfutwtgwzgkdbpjnrmllqbidmnsvdzefshccxvwqtxyvkqxhjrpzosr
"""

decoded = decoded(file_content.strip())
print(f"Decoded message: {decoded}")

